### ISSUE TITLE
"CI event" build trigger keeps creating threads on Jenkins when given invalid client name

### ISSUE THREAD

**Issue by wcheang** [jenkinsci/jms-messaging-plugin#118] opened 2019-03-19 20:40 UTC
Hi,

When given an invalid AMQ consumer name, e.g. Consumer.client-name.service.dev.VirtualTopic.eng.something.>, the jenkins job doesn't get triggered, but keeps creating threads non-stop. The thread number grows quickly and eventually eats up all the CPU on Jenkins. Disabling the job does not help eliminate the threads; we had to manually delete the threads on our jenkins monitoring, and actually the disabled job kept generating more threads.

Thanks,
Wai

**Comment by ggallen** [comment] 2019-03-19 20:47
Wai, I haven't seen this behavior. Can you point me to the Jenkins master and the job so I can take a look?

**Comment by sochotnicky** [comment] 2019-03-20 12:56
I actaully haven't seen that behaviour and I *think* I was noticing what Wai reported here. What I actually saw was that when invalid consumer is defined (for example queue where the client has no permissions to read) - it will result in a Thread that seems to spin on a few points eating a lot of CPU. When that consumer queue is fixed - the old Thread is not cleaned up however it seems. The only way seems to be to go to monitoring and kill it. 

I personally haven't seen creation of threads non-stop so perhaps Wai is talking about a separate issue

**Comment by ggallen** [comment] 2019-03-20 14:28
@sochotnicky , that's the behavior I have seen as well. If the connection fails, it will keep trying to connect every minute.  This is in fact desired behavior as if connectivity is lost for some reason we want it to reconnect when things are fixed.

We could handle the invalid consumer case and just stop the thread since that will *never* connect without a configuration change.  But how would the user ever know about it?

@wcheang , I did check the logs on your Jenkins and from what I can tell it was behaving as "expected" in that it was trying to reconnect every minute. As I already said, I've never seen the behavior you have described with all the threads being created. Can we set up a time to try it on your system so I can see it happening?

**Comment by sochotnicky** [comment] 2019-03-20 14:36
I want to be clear though - there *is* something wrong. The listener threads with wrong queues don't  sit idly for 1 minute. They spin on CPU full-tilt. And they don't get cleaned up when config changes.

**Comment by sochotnicky** [comment] 2019-03-20 14:39
@ggallen I can prep an example and we can test on our stage Jenkins instance (mostly any time). Will contact separately

**Comment by wcheang** [comment] 2019-03-20 15:46
I mixed up the high CPU time on the monitoring page with high thread count. Sorry about the confusion. But like Stano said there is definitely something wrong here since the client is eating up all the CPU.

**Comment by ggallen** [comment] 2019-03-20 17:22
OK, I have reproduced this and I see the problem. Now to figure out how to fix it....

I will keep you posted.

**Comment by ggallen** [comment] 2019-04-03 15:59
@wcheang , this is fixed in #119 .  Would you be willing to test it out?

**Comment by wcheang** [comment] 2019-04-03 17:12
Awesome, thanks a lot @ggallen! If there's an update yeah I can pull it in our jenkins and test it out.

**Closed** 2019-04-04 15:37 UTC
