### ISSUE TITLE
job configuration UI does not display saved settings

### ISSUE THREAD

**Issue by ktdreyer** [jenkinsci/jms-messaging-plugin#184] opened 2020-03-23 21:37 UTC
When I add or edit a "CI Notifier" publisher for a job, the web UI does not display the settings I've saved. This happens when I edit the job by hand with the web form and when I use Jenkins Job Builder.

**Versions:**
RHEL 7.6
Jenkins ver. 2.150.2
JMS Messaging Plugin 1.1.14

**Steps to reproduce:**
1) Create a new freestyle job.
2) At the bottom of the job, add a new "Post-build Actions" step. Select "CI Notifier".
3) Note that the UI displays the default settings, since this is a new Post-build Action. For example, the "Message type" dropdown defaults to "Custom", and the "Message properties" and "Message content" text fields are blank.
4) Change any one of the default settings. Example of things to change here:
  A) Pick a non-default connection in the dropdown.
  B) Set another "provider topic" other than the default value.
  C) Pick a Message type other than "Custom".
  D) Enter some value in the "Message properties" box so that it is not blank.
  E) Enter some value in the "Message content" box so that it is not blank.
5) Save the settings.
6) View the configuration page for the job.

**Actual results:**
The configuration page displays my CI Notifier, but it displays none of my custom settings.

**Expected results:**
The configuration UI page displays the settings I've saved to disk.

**Additional info:**
The job settings are correct on disk (eg. `/var/lib/jenkins/jobs/test/config.xml`), but the UI does not reflect the settings on disk.

For example, the job configuration on disk will contain "`<messageType>ImageUploaded</messageType>`", but the UI only displays a "Custom" Message type instead of "Image Uploaded".

**Comment by ktdreyer** [comment] 2020-03-23 21:48
I've upgraded through several LTS Jenkins versions to see if that helps. I confirmed this bug is present with each of the following:

Jenkins ver. 2.150.2
Jenkins ver. 2.150.3
Jenkins ver. 2.164.3
Jenkins ver. 2.176.4
Jenkins ver. 2.204.5

**Comment by scoheb** [comment] 2020-03-27 01:49
Hi,
This looks like a duplicate of #146 
I will try to look into these issues shortly with @ggallen

**Closed** 2020-04-09 13:57 UTC

**Comment by scoheb** [comment] 2020-04-09 15:29
Fix released in version 1.1.16

**Comment by ktdreyer** [comment] 2020-04-14 22:29
Thank you! This will help our users who are learning this plugin.

**Comment by ktdreyer** [comment] 2020-04-27 16:51
I've confirmed that the "CI Notifier" data looks correct in the web UI now with 1.1.16. Thanks.

**Comment by scoheb** [comment] 2020-04-27 20:20
@ktdreyer please note that using v1.1.18 is **highly** recommended!
