### ISSUE TITLE
fedmsg - timestamp format incorrect

### ISSUE THREAD

**Issue by jimbair** [jenkinsci/jms-messaging-plugin#166] opened 2020-02-07 21:25 UTC
Hi,

As part of our effort to migrate Fedora CI from fedmsg to FedoraMessaging, we updated our plugin to a newer version to support both fedmsg and FedoraMessaging. However, when we upgraded, the messages we saw were from the year 51850:

https://pagure.io/fedora-infrastructure/issue/8389

If I had to guess, it was the result of this change:

https://github.com/jenkinsci/jms-messaging-plugin/pull/131/files#diff-ced6de889db92a638334868a1246ff74R272

As a work-around, we deployed the following, which we hoped to be a temporary solution until we moved our triggers off of fedmsg:

https://github.com/bstinsonmhk/jms-messaging-plugin/commit/e24c97d117a33fb87680c5a7ac332a4243718b63

However, we're still working through it, so in hopes of moving back into the latest stable plugin, we wanted to see if we could get this fix (or one like it) merged in until we can migrate off completely.

Thank you!

**Comment by scoheb** [comment] 2020-02-10 15:05
FYI @Zlopez

**Comment by Zlopez** [comment] 2020-02-11 08:50
@jimbair Just to make it clear, you have the incorrect timestamp in Fedora Messaging message?

**Comment by bgoncalv** [comment] 2020-02-11 09:28
No, the problem is the timestamp only when publishing to FedMsg.

**Comment by Zlopez** [comment] 2020-02-11 13:24
I noticed the timestamp is set the same for Fedora Messaging, so I added the fix for this.

**Closed** 2020-02-19 13:38 UTC
